global:
  scrape_interval: 5s
  scrape_timeout:
scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: app
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
        - host.docker.internal:8888
